apiVersion : apps/v1
kind: Deployment
metadata:
  name: hellokubernetes 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hellokubernetes
  template:
    metadata:
      labels:
        app: hellokubernetes 
    spec:
      containers:
        - name: hellokubernetes 
          image: demoday.azurecr.io/saswatmohantyhellokubernetes
          ports:
          - containerPort: 8080
