apiVersion: v1
kind: Service
metadata:
  name: hellokubernetes
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hellokubernetes
